# Generated by Django 3.1.3 on 2022-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='body',
        ),
        migrations.AddField(
            model_name='groups',
            name='personList',
            field=models.CharField(default='daanzwarthoed', max_length=100),
            preserve_default=False,
        ),
    ]
