# Generated by Django 3.1.3 on 2022-01-11 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_groups_wordlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='wordList',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None),
        ),
    ]
